---
name: CI

on:
  push:
  pull_request:

jobs:
  run:
    strategy:
      matrix:
        include:
          - rust: nightly
          - rust: stable
            features: ""
          - rust: stable
            features: "rayon"
          - rust: beta
          - rust: 1.23.0

    runs-on: ubuntu-latest

    env:
      CARGO_ARGS: "-v --features ${{ matrix.features }}"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: "$CARGO_ARGS"

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: "$CARGO_ARGS"
          # testing requires building dev-deps, which require a newer Rust.
        if: matrix.rust != '1.23.0'

      - uses: actions-rs/cargo@v1
        with:
          command: bench
          # don't actually record numbers
          args: "$CARGO_ARGS -- --test"
        # testing requires building dev-deps, which require a newer Rust.
        if: matrix.rust != '1.23.0'

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: "$CARGO_ARGS"
